<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
?>
<script type="text/javascript">
require([
    'jquery',
    'jquery/ui',
    'jquery/validate',
    'mage/translate'
], function($){
	$.validator.addMethod(
		'validate-zero-custom', function (v) { 
			// Validation logic here
			return (v > 0); 
		}, $.mage.__('Updating the quantity with \'0\' will remove this item from the cart.'));
	});
</script>