<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php ini_set('display_errors','off'); ?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php
        $checkoutSession = $_SESSION['checkout'];
        $bufferSessions = $checkoutSession['buffer'];
        $orderId = $block->getOrderId();
        $orderIdFill = str_pad($orderId, 9, '0', STR_PAD_LEFT);
        $biffOrderId = 0;
        if (isset($bufferSessions)) {
            $bufferObject = json_decode($bufferSessions);
            if (is_object($bufferObject) && isset($bufferObject->properties->orderBatchId->type)) {
                $bufferResponse = (int) $bufferObject->properties->orderBatchId->type;
            } elseif (is_object($bufferObject) && isset($bufferObject->message)) {
                $bufferResponse = $bufferObject->message;
            }
        }
        ?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
        <?php if (empty($bufferResponse)) : echo '<!-- ' ; ?><?php endif;?>
        <p><?php echo __('Your BIF order # is: <span>%1</span>.', $bufferResponse) ?></p>
        <?php if (empty($bufferResponse)):  echo '--> ' ; ?><?php endif;?>
        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
