<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search top_toolbar">

<div class="mini-search-block ">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="top_toolbar_left"></div>
    <div class="top_toolbar_icons">
        <div class="phoneimg">
            <a href="#" class="top_phone_link" ></a>
        </div>
        <div class="shareicon">
            <a href="#" class="top_share_link"></a>
        </div>
        <div class="top_search_image">
            <div class="top_search_form block block-content">
                <div class="ioaSmallSearch_left"></div>
                <form class="form minisearch top_search_fieldset " id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                    <label class="label top_search_label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                    <input id="top_search_textbox"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search...'); ?>"
                           class="input-text "
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                    </div>
                    <div class="actions">
                        <button type="submit" id="top_search_button"
                                title="<?php echo $block->escapeHtml(__('Search')) ?>"
                                class="action search ">
                            <span class="top_search_text"><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="top_toolbar_right"></div>
</div>


