<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php
$adminConfHelper = $this->helper('Prokarma\Adminconf\Helper\Data');
$mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<!-- Contents for Cart Page-->
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cart-message')->toHtml();?>

<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
      class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif; ?>
        <h2><?php /* @escapeNotVerified */ echo __('Gift Cards') ?></h2>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
            <tr>
                <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Card') ?></span></th>
                <th class="col" scope="col"></th>
                <th class="col" scope="col"><span><?php /* @escapeNotVerified */ echo __('Customization') ?></span></th>
                <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></th>
                <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Card Value') ?></span></th>
                <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                <th class="col" scope="col"><span><?php /* @escapeNotVerified */ echo __('Purchase Fee(s)') ?></span></th>
                <th class="col" scope="col"></th>
            </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <?php $adminConfHelper = $this->helper('Prokarma\Adminconf\Helper\Data'); ?>
            <a class="action continue"
               href="<?php echo $adminConfHelper->getContinueShoppingLink('continue_redirect/redirectlink'); ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after') ?>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'Magento_Ui/js/modal/modal'
    ], function ($) {
        $("#update-cart-action").click(function(event) {
            var id = 0;
            var  itmTotal = 0;
            var  itmQty = 0;
            <?php foreach($block->getQuote()->getAllVisibleItems() as $item): ?>
                id = parseInt('<?php echo $item->getId(); ?>');
                itmTotal = itmTotal + parseInt($('#cart-' + id + '-qty').val()) * parseInt($('#cart-' + id + '-price').val());
                itmQty = itmQty + $('#cart-' + id + '-qty').val();
            <?php endforeach; ?>
            if (itmQty >= parseInt('<?php echo $adminConfHelper->getThresholdConfig('threshold/quantity'); ?>')
                && itmTotal >= parseInt('<?php echo $adminConfHelper->getThresholdConfig('threshold/value'); ?>')
            ) {
                $('<div />').html('<?php echo $adminConfHelper->getThresholdConfig('threshold/message'); ?>')
                    .modal({
                        title: '<?php echo $adminConfHelper->getThresholdConfig('threshold/title'); ?>',
                        autoOpen: true,
                        closed: function () {
                        },
                        buttons: []
                    });
                event.preventDefault();
            } else {
                $(".form-cart").submit();
            }
        });
    });
</script>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cart-message')->toHtml();?>